databases:
  - name: postgres
    ipAllowList: []
    plan: free
    databaseName: outdoor_adventures_render
    user: outdoor_adventures_render

services:
  - type: web
    name: outdoor_adventures
    plan: free
    env: ruby
    buildCommand: './render-build.sh'
    startCommand: 'bundle exec rails s'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
