---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/adventures":
    get:
      summary: Get index of adventures
      tags:
      - Adventures
      responses:
        '200':
          description: List of adventures retrieved
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: text
                    picture:
                      type: string
                    created_at:
                      type: datetime
                    updated_at:
                      type: datetime
                  required:
                  - id
                  - name
                  - picture
                  - description
  "/api/v1/reservations":
    post:
      summary: Create Reservations
      tags:
      - Create Reservations
      parameters: []
      responses:
        '201':
          description: Reservation created successfully
        '204':
          description: No reservation found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currentUserID:
                  type: integer
                adventureID:
                  type: integer
              required:
              - currentUserID
              - adventureID
  "/api/v1/fetch_reservations":
    post:
      summary: Fetch Reservations
      tags:
      - Reservations
      parameters: []
      responses:
        '200':
          description: Reservations fetched successfully
        '204':
          description: No reservation found
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                currentUserID:
                  type: integer
              required:
              - currentUserID
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000/
